#!/bin/bash

_package_update_installed=1

function _package_update_verify {
    # for now just limit executing this to once per run
    return ${_package_update_installed}
}

function _package_update {
    local retval

    sudo apt-get update ${package} && _package_update_installed=0

    # verify installation
    _package_update_verify ${@}
    retval=$?

    return ${retval}
}
