#!/bin/bash

function _bash_path_verify {
    local path=${1}

    grep -e "^PATH=.*:${path}" -e "^PATH=${path}:.*$" -e "^PATH=.*:${path}:.*$" -e "^PATH=${path}$" ~/.bashrc || return 1

    return 0
}

function _bash_path {
    local retval

    local path=${1}

    if grep "^PATH=" ~/.bashrc &> /dev/null ; then
        if ! grep -e "^PATH=.*:${path}" -e "^PATH=${path}:.*$" -e "^PATH=.*:${path}:.*$" -e "^PATH=${path}$" ~/.bashrc &> /dev/null ; then
            path=$(echo ${path} | sed 's/\//\\\//g')
            sed -i "s/^PATH=/PATH=${path}\:/" ~/.bashrc
        fi
    else
        echo "PATH=${path}:\${PATH}" >> ~/.bashrc
    fi

    # verify installation
    _bash_path_verify $@ ; retval=$?
    if [[ ! ${retval} -eq 0 ]] ; then
        log error "bash_path ${path} failed"
    fi

    return ${retval}
}
