#!/bin/bash

function bash_variable_verify {
    local variable=${1}
    local value=${2}

    if [[ -z ${variable} ]] ; then return 1; fi

    echo "source ${HOME}/.bashrc ; [[ \"\${${variable}}\" == \"${value}\" ]]" | bash -i &> /dev/null
    return $?
}

function bash_variable {
    local retval

    local variable=${1}
    local value=${2}

    if [[ -z ${variable} ]] ; then return 1; fi

    if grep "^export ${variable}=" ${HOME}/.bashrc ; then
        sed -i "s/^export ${variable}=.*/export ${variable}='${value}'/" ${HOME}/.bashrc
    else
        echo "export ${variable}='${value}'" >> ${HOME}/.bashrc
    fi

    # verify installation
    bash_variable_verify "${variable}" "${value}" ; retval=$?
    if [[ ! ${retval} -eq 0 ]] ; then
        log error "${variable}=${value} failed"
    fi

    return ${retval}
}
